#!/bin/sh
### BEGIN INIT INFO
# Provides:          liteflow
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Monitor for liteflow activity
# Description:       LiteFlow Port Forwarder
### END INIT INFO

# This script is used for /etc/init.d management.

# **NOTE** bash will exit immediately if any command exits with non-zero.
set -e

PACKAGE_NAME=liteflow
PACKAGE_DESC="LiteFlow Port Forwarder"
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:${PATH}

BIN="/usr/bin/liteflow -c /path/to/config"
PID_FILE="/var/run/liteflow.pid"

start() {
    echo -n "Starting ${PACKAGE_DESC}: "
    ulimit -c unlimited
    ulimit -n 65536
    if [ ! -d /etc/logrotate.d ]; then
        nohup /usr/bin/env TZ=Asia/Shanghai $BIN 2>&1 | /usr/bin/logger -t ${PACKAGE_NAME} &
    else
        if [ ! -f /etc/logrotate.d/liteflow ]; then
            cat > /etc/logrotate.d/liteflow <<EOF
/var/log/liteflow.log {
    daily
    rotate 7
    size=100k
    compress
    copytruncate
    missingok
    notifempty
    nocreate
    postrotate
    endscript
}
EOF
        fi
        nohup /usr/bin/env TZ=Asia/Shanghai $BIN 2>&1 >> /var/log/liteflow.log &
    fi
    echo $! > $PID_FILE
    echo "${PACKAGE_NAME}."
}

stop() {
    echo -n "Stopping ${PACKAGE_DESC}: "
    if [ -f $PID_FILE ]; then
        kill -9 `cat $PID_FILE` >/dev/null 2>&1 || true
        rm $PID_FILE
    fi
    echo "${PACKAGE_NAME}."
}

reload() {
    echo -n "Reloading ${PACKAGE_DESC}: "
    if [ -f $PID_FILE ]; then
        kill -10 `cat $PID_FILE` >/dev/null 2>&1 || true
    fi  
    echo "${PACKAGE_NAME}."
}

restart() {
    stop || true
    sleep 1
    start
}

check_pid() {
    
}

status() {
    if [ ! -f "$PID_FILE" ]; then
        log "${PACKAGE_DESC} is not running (no PID file)"
        exit 1
    fi

    PID=$(cat "$PID_FILE")
    if ! [[ "$PID" =~ ^[0-9]+$ ]]; then
        log "Error: Invalid PID value in $PID_FILE"
        exit 1
    fi

    if kill -0 "$PID" 2>/dev/null; then
        log "${PACKAGE_DESC} is running (PID $(cat $PID_FILE))"
        exit 0
    else
        log "${PACKAGE_DESC} is not running (stale PID file)"
        exit 1
    fi
}

usage() {
    N=$(basename "$0")
    echo "Usage: [sudo] $N {start|stop|reload|restart|status}" >&2
    exit 1
}

if [ "$(id -u)" != "0" ]; then
    echo "please use sudo to run ${PACKAGE_NAME}"
    exit 0
fi

# `readlink -f` won't work on Mac, this hack should work on all systems.

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload)
        reload
        ;;
    restart | force-reload)
        restart
        ;;
    status)
        status
        ;;
    *)
        usage
        ;;
esac

exit 0
